[package]
name = "emp-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
bson = "2.13.0"
chrono = "0.4.39"
mongodb = "3.1.1"
serde = "1.0.216"
tokio = "1.42.0"
futures-util = "0.3.30"
sha2 = "0.10.8"
env_logger = "0.11.6"
jwt = "0.16.0"
hmac = "0.12.1"